In [1]:
# connect to google drive
from google.colab import drive
drive.mount('/content/gdrive')

# call all functions used in starter file
%run "/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/ImportFilesAndFunctions.ipynb"

Mounted at /content/gdrive
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 38.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 54.1 MB/s eta 0:00:00

INFO:lightning_fabric.utilities.seed:Seed set to 42

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
All imports successful!

In [2]:
# load the dataset
palmoil_df = pd.read_csv('/content/gdrive/MyDrive/PalmWatch/data/hex_deforestation_forecast.csv')

# check for any null values
palmoil_df[palmoil_df.isnull().any(axis=1)]

# fills all empty/na/nan values (usually provinces with no neighbors) with 0
palmoil_df.fillna(0, inplace=True)

In [3]:
# drop years that we need to predict
palmoil_wo_target = palmoil_df[palmoil_df['year'] <= 2018]

In [4]:
# list with features and targets
feature_names = ['defor_frac', 'degr_frac', 'remaining_frac_baseline', 'remaining_frac_hex', 'remaining_forest_ha', 'nbr_r1_defor_frac', 'nbr_r2_defor_frac' , 'nbr_r1_remaining_frac_baseline', 'target_total_5yr' , 'target_palm_5yr']

# colloquial names for every feature
common_names = ['Fraction of Deforestation', 'Fraction of Degradation', 'Cumulative Remaining Forest', 'Current Forest Density', 'Remaining Forest (hectacres)', 'Neighboring 6 Deforestation Fraction', 'Neighboring 12 Deforestation Fraction', 'Average Neighboring Remaining Forest' , 'Predicted 5 Year Deforestation', 'Predicted 5 Year Deforestation for Palm Oil']

# list of all provinces
provinces = ['Aceh', 'SumateraUtara', 'Riau', 'SumateraBarat', 'Lampung', 'SumateraSelatan', 'Jambi', 'Bengkulu']

# year range of our dataset
YEARS = range(2000, 2019)

In [5]:
# function to create a dataframe of a specific province and year
def sortByProvince(province, df, year):
  """Create a new dataframe and return all rows of a specific province and specific year"""
  new_df = df[(df['province'] == province) & (df['year'] == year)]

  return new_df

In [6]:
# function to loop through all features and find the median of a group of 16 hex id's
def create_subsetted_data(province, df, year, feature_names, group_size=16):
  """Creates a new dataframe that finds the median of a group of 16 hex_id"""
  province_df = sortByProvince(province, df, year)

  subsetted_data = {
      "Grouped ID": [],
      "Year": []
  }

  for feature in feature_names:
      subsetted_data[f"{feature}_median"] = []

  for i in range(0, len(province_df), group_size):
      subsetted_data["Grouped ID"].append(i // group_size)
      subsetted_data["Year"].append(year)

      for feature in feature_names:
          subsetted_data[f"{feature}_median"].append(
              province_df[feature].iloc[i:i+group_size].median()
          )

  return pd.DataFrame(subsetted_data)

In [7]:
# creates a dataframe with all years of a specific province
def create_all_years_data(province, df, years, feature_names, group_size=16):
  """Creates a dataframe with all years of a specific province"""
  all_data = []
  df = df.sort_values(['year', 'province', 'lat', 'lon'])

  for year in years:
      yearly_df = create_subsetted_data(
          province,
          df,
          year,
          feature_names,
          group_size
      )
      all_data.append(yearly_df)

  return pd.concat(all_data, ignore_index=True)

In [8]:
# create a new dataframe province by province of a larger grouped area

# creates a dataframe with aceh
combined_aceh = create_all_years_data(
    province="Aceh",
    df=palmoil_wo_target,
    years=YEARS,
    feature_names=feature_names
)

combined_aceh.insert(2, 'Province', 'Aceh')

# creates a dataframe with sumatera utara
combined_sumaterautara = create_all_years_data(
    province="SumateraUtara",
    df=palmoil_wo_target,
    years=YEARS,
    feature_names=feature_names
)

combined_sumaterautara.insert(2, 'Province', 'SumateraUtara')

# creates a dataframe with riau
combined_riau = create_all_years_data(
    province="Riau",
    df=palmoil_wo_target,
    years=YEARS,
    feature_names=feature_names
)

combined_riau.insert(2, 'Province', 'Riau')

# creates a dataframe with sumatera barat
combined_sumaterabarat = create_all_years_data(
    province="SumateraBarat",
    df=palmoil_wo_target,
    years=YEARS,
    feature_names=feature_names
)

combined_sumaterabarat.insert(2, 'Province', 'SumateraBarat')

# creates a dataframe with lampung
combined_lampung = create_all_years_data(
    province="Lampung",
    df=palmoil_wo_target,
    years=YEARS,
    feature_names=feature_names
)

combined_lampung.insert(2, 'Province', 'Lampung')

# creates a dataframe with sumatera selatan
combined_sumateraselatan = create_all_years_data(
    province="SumateraSelatan",
    df=palmoil_wo_target,
    years=YEARS,
    feature_names=feature_names
)

combined_sumateraselatan.insert(2, 'Province', 'SumateraSelatan')

# creates a dataframe with jambi
combined_jambi = create_all_years_data(
    province="Jambi",
    df=palmoil_wo_target,
    years=YEARS,
    feature_names=feature_names
)

combined_jambi.insert(2, 'Province', 'Jambi')

# creates a dataframe with bengkulu
combined_bengkulu = create_all_years_data(
    province="Bengkulu",
    df=palmoil_wo_target,
    years=YEARS,
    feature_names=feature_names
)

combined_bengkulu.insert(2, 'Province', 'Bengkulu')

In [9]:
def create_lag_features(df, features, lags=2):
  df = df.sort_values("year").copy()

  for feature in features:
      for lag in range(1, lags+1):
          df[f"{feature}_lag{lag}"] = df[feature].shift(lag)

  return df

In [10]:
aceh = palmoil_wo_target[palmoil_wo_target['province'] == 'Aceh']
aceh_18yr = aceh.groupby('year', as_index=False)[feature_names].mean()

sumaterautara = palmoil_wo_target[palmoil_wo_target['province'] == 'SumateraUtara']
sumaterautara_18yr = sumaterautara.groupby('year', as_index=False)[feature_names].mean()

riau = palmoil_wo_target[palmoil_wo_target['province'] == 'Riau']
riau_18yr = riau.groupby('year', as_index=False)[feature_names].mean()

sumaterabarat = palmoil_wo_target[palmoil_wo_target['province'] == 'SumateraBarat']
sumaterabarat_18yr = sumaterabarat.groupby('year', as_index=False)[feature_names].mean()

lampung = palmoil_wo_target[palmoil_wo_target['province'] == 'Lampung']
lampung_18yr = lampung.groupby('year', as_index=False)[feature_names].mean()

sumateraselatan = palmoil_wo_target[palmoil_wo_target['province'] == 'SumateraSelatan']
sumateraselatan_18yr = sumateraselatan.groupby('year', as_index=False)[feature_names].mean()

jambi = palmoil_wo_target[palmoil_wo_target['province'] == 'Jambi']
jambi_18yr = jambi.groupby('year', as_index=False)[feature_names].mean()

bengkulu = palmoil_wo_target[palmoil_wo_target['province'] == 'Bengkulu']
bengkulu_18yr = bengkulu.groupby('year', as_index=False)[feature_names].mean()

In [11]:
full_provinces = [aceh, sumaterautara, riau, sumaterabarat, lampung, sumateraselatan, jambi, bengkulu]

full_provinces_18yr = [aceh_18yr, sumaterautara_18yr, riau_18yr, sumaterabarat_18yr, lampung_18yr, sumateraselatan_18yr, jambi_18yr, bengkulu_18yr]

In [27]:
palm_forecast_dfs = {}
total_forecast_dfs = {}

## PALM OIL DEFORESTATION DATAFRAME

In [32]:
for province in provinces:
  print(province)
  display(palm_forecast_dfs[province])

Aceh

    Year  Palm Oil
0   2000  0.011025
1   2001  0.011115
2   2002  0.011625
3   2003  0.015949
4   2004  0.017826
5   2005  0.018112
6   2006  0.020195
7   2007  0.020443
8   2008  0.019329
9   2009  0.019280
10  2010  0.018361
11  2011  0.015480
12  2012  0.013431
13  2013  0.009767
14  2014  0.012675
15  2015  0.024850
16  2016  0.019967
17  2017  0.021770
18  2018  0.021929
19  2019  0.021929
20  2020  0.021929
21  2021  0.021929
22  2022  0.021929
23  2023  0.021929

SumateraUtara

    Year  Palm Oil
0   2000  0.068484
1   2001  0.072039
2   2002  0.074606
3   2003  0.080049
4   2004  0.082583
5   2005  0.082529
6   2006  0.088597
7   2007  0.088278
8   2008  0.087397
9   2009  0.081724
10  2010  0.077614
11  2011  0.068355
12  2012  0.066635
13  2013  0.050728
14  2014  0.054881
15  2015  0.083521
16  2016  0.073081
17  2017  0.073081
18  2018  0.082814
19  2019  0.082814
20  2020  0.082814
21  2021  0.082814
22  2022  0.082814
23  2023  0.082814

Riau

    Year  Palm Oil
0   2000  0.087419
1   2001  0.100731
2   2002  0.107296
3   2003  0.120940
4   2004  0.123021
5   2005  0.112356
6   2006  0.101352
7   2007  0.098119
8   2008  0.092045
9   2009  0.078266
10  2010  0.070478
11  2011  0.064410
12  2012  0.053244
13  2013  0.072338
14  2014  0.075673
15  2015  0.149298
16  2016  0.140236
17  2017  0.150457
18  2018  0.166678
19  2019  0.166678
20  2020  0.166678
21  2021  0.165999
22  2022  0.165999
23  2023  0.165999

SumateraBarat

    Year  Palm Oil
0   2000  0.020230
1   2001  0.021023
2   2002  0.022038
3   2003  0.025891
4   2004  0.024577
5   2005  0.023604
6   2006  0.022945
7   2007  0.021271
8   2008  0.017572
9   2009  0.015797
10  2010  0.015004
11  2011  0.012498
12  2012  0.011657
13  2013 -0.012240
14  2014  0.017390
15  2015  0.012245
16  2016 -0.008864
17  2017  0.015876
18  2018  0.012245
19  2019 -0.008864
20  2020  0.015876
21  2021  0.012245
22  2022 -0.008864
23  2023  0.015876

Lampung

    Year  Palm Oil
0   2000  0.004199
1   2001  0.004426
2   2002  0.003731
3   2003  0.003720
4   2004  0.003989
5   2005  0.004054
6   2006  0.003679
7   2007  0.003826
8   2008  0.003908
9   2009  0.000479
10  2010  0.000500
11  2011  0.000443
12  2012  0.000301
13  2013 -0.000088
14  2014 -0.000088
15  2015 -0.000088
16  2016 -0.000088
17  2017 -0.000088
18  2018 -0.000088
19  2019 -0.000088
20  2020 -0.000088
21  2021 -0.000088
22  2022 -0.000088
23  2023 -0.000088

SumateraSelatan

    Year  Palm Oil
0   2000  0.022016
1   2001  0.027570
2   2002  0.030420
3   2003  0.035029
4   2004  0.036452
5   2005  0.037314
6   2006  0.035332
7   2007  0.038606
8   2008  0.036638
9   2009  0.032303
10  2010  0.031340
11  2011  0.027180
12  2012  0.016931
13  2013  0.046941
14  2014  0.035100
15  2015  0.050100
16  2016  0.045035
17  2017  0.048193
18  2018  0.045035
19  2019  0.048193
20  2020  0.045035
21  2021  0.048193
22  2022  0.045035
23  2023  0.048193

Jambi

    Year  Palm Oil
0   2000  0.033489
1   2001  0.038954
2   2002  0.040365
3   2003  0.050173
4   2004  0.048173
5   2005  0.045990
6   2006  0.042986
7   2007  0.043708
8   2008  0.038908
9   2009  0.034164
10  2010  0.034342
11  2011  0.031382
12  2012  0.025160
13  2013  0.007219
14  2014  0.007219
15  2015  0.124336
16  2016  0.121289
17  2017  0.116950
18  2018  0.305920
19  2019  0.264973
20  2020  0.240791
21  2021  0.237070
22  2022  0.241216
23  2023  0.229308

Bengkulu

    Year  Palm Oil
0   2000  0.028364
1   2001  0.028977
2   2002  0.030091
3   2003  0.032562
4   2004  0.028812
5   2005  0.027907
6   2006  0.027798
7   2007  0.024969
8   2008  0.021941
9   2009  0.019803
10  2010  0.018688
11  2011  0.014572
12  2012  0.012702
13  2013  0.096977
14  2014  0.082702
15  2015  0.173987
16  2016  0.102622
17  2017  0.227736
18  2018  0.169877
19  2019  0.227736
20  2020  0.277582
21  2021  0.275077
22  2022  0.316530
23  2023  0.316530

In [31]:
palm_forecast_dfs['Aceh']

    Year  Palm Oil
0   2000  0.011025
1   2001  0.011115
2   2002  0.011625
3   2003  0.015949
4   2004  0.017826
5   2005  0.018112
6   2006  0.020195
7   2007  0.020443
8   2008  0.019329
9   2009  0.019280
10  2010  0.018361
11  2011  0.015480
12  2012  0.013431
13  2013  0.009767
14  2014  0.012675
15  2015  0.024850
16  2016  0.019967
17  2017  0.021770
18  2018  0.021929
19  2019  0.021929
20  2020  0.021929
21  2021  0.021929
22  2022  0.021929
23  2023  0.021929

## TOTAL DEFORESTATION DATAFRAMES

In [33]:
for province in provinces:
  print(province)
  display(total_forecast_dfs[province])

Aceh

    Year  Total Deforestation
0   2000             0.037387
1   2001             0.034874
2   2002             0.034121
3   2003             0.044577
4   2004             0.049114
5   2005             0.049545
6   2006             0.054936
7   2007             0.057943
8   2008             0.058813
9   2009             0.066768
10  2010             0.068623
11  2011             0.065435
12  2012             0.062975
13  2013             0.057393
14  2014             0.042585
15  2015             0.036285
16  2016             0.032515
17  2017             0.031295
18  2018             0.026589
19  2019             0.031839
20  2020             0.031510
21  2021             0.047798
22  2022             0.044834
23  2023             0.057588

SumateraUtara

    Year  Total Deforestation
0   2000             0.116569
1   2001             0.115971
2   2002             0.117478
3   2003             0.127660
4   2004             0.133425
5   2005             0.134941
6   2006             0.144872
7   2007             0.145103
8   2008             0.145790
9   2009             0.144657
10  2010             0.141871
11  2011             0.130207
12  2012             0.128058
13  2013             0.121734
14  2014             0.112979
15  2015             0.100384
16  2016             0.098654
17  2017             0.095986
18  2018             0.090037
19  2019             0.225929
20  2020             0.248207
21  2021             0.244990
22  2022             0.244990
23  2023             0.244990

Riau

    Year  Total Deforestation
0   2000             0.204975
1   2001             0.227133
2   2002             0.237137
3   2003             0.263893
4   2004             0.262939
5   2005             0.249325
6   2006             0.247931
7   2007             0.260324
8   2008             0.279010
9   2009             0.276618
10  2010             0.263184
11  2011             0.248032
12  2012             0.219494
13  2013             0.177262
14  2014             0.153825
15  2015             0.139403
16  2016             0.130631
17  2017             0.131187
18  2018             0.114989
19  2019             0.100413
20  2020             0.106182
21  2021             0.105091
22  2022             0.100743
23  2023             0.082633

SumateraBarat

    Year  Total Deforestation
0   2000             0.047865
1   2001             0.050376
2   2002             0.051765
3   2003             0.062226
4   2004             0.062645
5   2005             0.060232
6   2006             0.061464
7   2007             0.061570
8   2008             0.059161
9   2009             0.057884
10  2010             0.061440
11  2011             0.058813
12  2012             0.060117
13  2013             0.056211
14  2014             0.056378
15  2015             0.050712
16  2016             0.049050
17  2017             0.048345
18  2018             0.045148
19  2019             0.092897
20  2020             0.101321
21  2021             0.101321
22  2022             0.103623
23  2023             0.103623

Lampung

    Year  Total Deforestation
0   2000             0.080491
1   2001             0.090115
2   2002             0.060955
3   2003             0.061267
4   2004             0.057658
5   2005             0.055442
6   2006             0.047977
7   2007             0.060111
8   2008             0.061116
9   2009             0.055666
10  2010             0.070550
11  2011             0.061160
12  2012             0.047723
13  2013             0.046054
14  2014             0.042559
15  2015             0.023133
16  2016             0.021789
17  2017             0.019788
18  2018             0.019684
19  2019             0.030496
20  2020             0.026870
21  2021             0.035203
22  2022             0.033961
23  2023             0.035482

SumateraSelatan

    Year  Total Deforestation
0   2000             0.116629
1   2001             0.141730
2   2002             0.144697
3   2003             0.163350
4   2004             0.169075
5   2005             0.170191
6   2006             0.160154
7   2007             0.187098
8   2008             0.188439
9   2009             0.182499
10  2010             0.211082
11  2011             0.205227
12  2012             0.164041
13  2013             0.147863
14  2014             0.137466
15  2015             0.091846
16  2016             0.078753
17  2017             0.081256
18  2018             0.083750
19  2019             0.094909
20  2020             0.114851
21  2021             0.106817
22  2022             0.096864
23  2023             0.107000

Jambi

    Year  Total Deforestation
0   2000             0.095891
1   2001             0.112527
2   2002             0.118899
3   2003             0.145860
4   2004             0.141069
5   2005             0.133315
6   2006             0.123905
7   2007             0.130563
8   2008             0.125553
9   2009             0.121296
10  2010             0.133899
11  2011             0.141686
12  2012             0.129898
13  2013             0.115941
14  2014             0.120683
15  2015             0.111029
16  2016             0.105211
17  2017             0.114229
18  2018             0.119888
19  2019             0.062697
20  2020             0.087867
21  2021             0.111126
22  2022             0.144592
23  2023             0.141509

Bengkulu

    Year  Total Deforestation
0   2000             0.086071
1   2001             0.088622
2   2002             0.087038
3   2003             0.097503
4   2004             0.086116
5   2005             0.084831
6   2006             0.086352
7   2007             0.088835
8   2008             0.086653
9   2009             0.088866
10  2010             0.103380
11  2011             0.095004
12  2012             0.094614
13  2013             0.092948
14  2014             0.090846
15  2015             0.077087
16  2016             0.074350
17  2017             0.072259
18  2018             0.070094
19  2019            -0.007740
20  2020             0.001350
21  2021             0.053667
22  2022             0.031215
23  2023             0.006947